---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mft
spec:
  selector: {app: redis}
  ports:
  - {port: 6379, targetPort: 6379}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mft
spec:
  replicas: 1
  selector:
    matchLabels: {app: redis}
  template:
    metadata:
      labels: {app: redis}
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command:
          - redis-server
          - --appendonly yes
          - --appendfsync everysec
          - --save 60 1
          - --maxmemory 256mb
          - --maxmemory-policy allkeys-lru
        ports:
        - {containerPort: 6379}
        resources:
          requests: {memory: "64Mi",  cpu: "50m"}
          limits:   {memory: "512Mi", cpu: "500m"}
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
        - {name: data, mountPath: /data}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pvc
