package com.filetransfer.ai.entity.intelligence;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Indicator of Compromise (IOC) entity for the threat intelligence store.
 *
 * <p>Each record represents a single observable artefact (IP address, domain, file
 * hash, CVE, JA3/JA4 fingerprint, etc.) that has been reported by one or more
 * threat intelligence feeds as potentially or confirmed malicious.</p>
 *
 * <h3>Lifecycle</h3>
 * <ol>
 *   <li>Ingested from an external threat feed or generated by internal detection logic.</li>
 *   <li>Enriched with confidence scores, MITRE ATT&amp;CK mappings, and contextual metadata.</li>
 *   <li>Matched against live file-transfer telemetry during real-time verdict computation.</li>
 *   <li>Sightings and false-positive counts updated on each match to tune confidence.</li>
 *   <li>Stale indicators (no sightings beyond configured max age) are aged out.</li>
 * </ol>
 *
 * @see IndicatorType
 * @see ThreatLevel
 */
@Entity
// R125: entity table name was "intel_threat_indicators" but V15 migration
// creates "threat_indicators" and the ai-engine readiness schema expects the
// same. Any live read attempt on this entity against a V15-provisioned DB
// failed with "relation intel_threat_indicators does not exist". Aligned with
// the migration + readiness contract.
@Table(name = "threat_indicators", indexes = {
        @Index(name = "idx_iti_type_value", columnList = "type,value", unique = true),
        @Index(name = "idx_iti_threat_level", columnList = "threatLevel"),
        @Index(name = "idx_iti_last_seen", columnList = "lastSeen"),
        @Index(name = "idx_iti_first_seen", columnList = "firstSeen")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ThreatIndicator {

    @Id
    @Column(updatable = false, nullable = false)
    private UUID iocId;

    /** The indicator classification (IP, DOMAIN, HASH_SHA256, etc.). */
    @Enumerated(EnumType.STRING)
    @Column(length = 30, nullable = false)
    private IndicatorType type;

    /** The observable value (IP address, domain name, hash digest, etc.). */
    @Column(nullable = false, length = 2048)
    private String value;

    /** Assessed threat severity. */
    @Enumerated(EnumType.STRING)
    @Column(length = 10)
    private ThreatLevel threatLevel;

    /** Confidence that this indicator is a true positive, 0.0 to 1.0. */
    private double confidence;

    /** Comma-separated feed / source names that reported this indicator. */
    @Column(columnDefinition = "TEXT")
    private String sources;

    /** Earliest observation across all sources. */
    private Instant firstSeen;

    /** Most recent observation or sighting. */
    private Instant lastSeen;

    /** Comma-separated free-form tags for categorisation and filtering. */
    @Column(columnDefinition = "TEXT")
    private String tags;

    /** Comma-separated MITRE ATT&amp;CK technique IDs associated with this IOC. */
    @Column(columnDefinition = "TEXT")
    private String mitreTechniques;

    /** Number of times this IOC was matched against live telemetry. */
    private int sightings;

    /** Number of times an analyst marked a match as a false positive. */
    private int falsePositiveCount;

    /** Arbitrary structured context (campaigns, malware family, etc.) stored as JSON. */
    @Column(columnDefinition = "TEXT")
    private String contextJson;

    // ── JPA Lifecycle Callbacks ──────────────────────────────────────────

    @PrePersist
    void prePersist() {
        if (iocId == null) {
            iocId = UUID.randomUUID();
        }
        if (firstSeen == null) {
            firstSeen = Instant.now();
        }
        lastSeen = Instant.now();
    }

    // ── Convenience Methods ─────────────────────────────────────────────

    /**
     * Increments the sighting counter and refreshes {@code lastSeen}.
     */
    public void incrementSightings() {
        this.sightings++;
        this.lastSeen = Instant.now();
    }

    /**
     * Returns {@code true} if this indicator has not been sighted within
     * the specified number of days, measured from {@code lastSeen}.
     *
     * @param maxDays maximum acceptable days since last sighting
     * @return whether the indicator should be considered stale
     */
    public boolean isStale(int maxDays) {
        if (lastSeen == null) {
            return true;
        }
        return lastSeen.isBefore(Instant.now().minus(Duration.ofDays(maxDays)));
    }

    /**
     * Computes an effective confidence score that accounts for false-positive
     * feedback.  The raw confidence is reduced proportionally to the FP ratio.
     *
     * @return adjusted confidence in [0.0, 1.0]
     */
    public double getEffectiveConfidence() {
        if (sightings == 0) {
            return confidence;
        }
        double fpRatio = (double) falsePositiveCount / sightings;
        return Math.max(0.0, confidence * (1.0 - fpRatio));
    }

    /**
     * Returns the source feed names as an immutable list.
     */
    public List<String> getSourcesList() {
        return splitCsv(sources);
    }

    /**
     * Returns the MITRE technique IDs as an immutable list.
     */
    public List<String> getMitreTechniquesList() {
        return splitCsv(mitreTechniques);
    }

    /**
     * Returns the tags as an immutable list.
     */
    public List<String> getTagsList() {
        return splitCsv(tags);
    }

    /**
     * Adds a source feed name if not already present.
     *
     * @param source the source name to add
     */
    public void addSource(String source) {
        if (source == null || source.isBlank()) return;
        sources = appendCsvUnique(sources, source.strip());
    }

    /**
     * Adds a tag if not already present.
     *
     * @param tag the tag to add
     */
    public void addTag(String tag) {
        if (tag == null || tag.isBlank()) return;
        tags = appendCsvUnique(tags, tag.strip());
    }

    /**
     * Adds a MITRE technique ID if not already present.
     *
     * @param techniqueId the MITRE technique ID (e.g., T1566.001)
     */
    public void addMitreTechnique(String techniqueId) {
        if (techniqueId == null || techniqueId.isBlank()) return;
        mitreTechniques = appendCsvUnique(mitreTechniques, techniqueId.strip());
    }

    /**
     * Merges another indicator's metadata into this one.
     * Takes the maximum threat level, merges sources and tags,
     * takes the higher confidence, and increments sightings.
     *
     * @param other the indicator to merge from
     */
    public void mergeFrom(ThreatIndicator other) {
        if (other == null) return;

        // Take max threat level
        if (other.threatLevel != null && (this.threatLevel == null
                || other.threatLevel.ordinal() > this.threatLevel.ordinal())) {
            this.threatLevel = other.threatLevel;
        }

        // Take max confidence
        if (other.confidence > this.confidence) {
            this.confidence = other.confidence;
        }

        // Merge sources
        if (other.sources != null) {
            for (String src : other.getSourcesList()) {
                addSource(src);
            }
        }

        // Merge tags
        if (other.tags != null) {
            for (String tag : other.getTagsList()) {
                addTag(tag);
            }
        }

        // Merge MITRE techniques
        if (other.mitreTechniques != null) {
            for (String tech : other.getMitreTechniquesList()) {
                addMitreTechnique(tech);
            }
        }

        // Increment sightings
        this.sightings++;
        this.lastSeen = Instant.now();
    }

    // ── Private Utilities ───────────────────────────────────────────────

    private static List<String> splitCsv(String csv) {
        if (csv == null || csv.isBlank()) {
            return Collections.emptyList();
        }
        return Arrays.stream(csv.split(","))
                .map(String::strip)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toUnmodifiableList());
    }

    private static String appendCsvUnique(String csv, String value) {
        if (csv == null || csv.isBlank()) {
            return value;
        }
        List<String> existing = new ArrayList<>(splitCsv(csv));
        if (!existing.contains(value)) {
            existing.add(value);
        }
        return String.join(",", existing);
    }
}
