apiVersion: v1
kind: Secret
metadata:
  name: mft-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mft.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.global.postgresql.password | quote }}
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  control-api-key: {{ .Values.global.controlApiKey | quote }}
  license-admin-key: {{ .Values.global.licenseAdminKey | quote }}
  encryption-master-key: {{ .Values.encryptionService.encryptionMasterKey | default "0000000000000000000000000000000000000000000000000000000000000000" | quote }}
