package com.filetransfer.ai.service.agent;

import com.filetransfer.ai.entity.threat.SecurityEnums.ThreatLevel;
import com.filetransfer.ai.service.proxy.IpReputationService;
import com.filetransfer.ai.service.proxy.IpReputationService.IpReputation;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * Correlates security events across multiple sources to detect coordinated
 * attack campaigns and advanced persistent threats (APTs).
 *
 * <p>Runs every 2 minutes. Analyzes:
 * <ul>
 *   <li>IPs appearing in multiple threat feeds (multi-source corroboration)</li>
 *   <li>Kill chain progression following MITRE ATT&amp;CK tactics</li>
 *   <li>Temporal clustering of related alerts</li>
 *   <li>Campaign tracking and progression over time</li>
 * </ul>
 *
 * <p>When 3+ stages of the kill chain are detected from a single source,
 * a HIGH-severity correlated alert is generated. Campaigns are tracked
 * across correlation windows to detect slow-and-low attacks.
 */
@Component
@Slf4j
public class ThreatCorrelationAgent extends BackgroundAgent {

    /**
     * MITRE ATT&CK tactic progression stages in typical kill chain order.
     * Each tag maps to a numeric stage for progression detection.
     */
    private static final Map<String, Integer> KILL_CHAIN_STAGES = Map.ofEntries(
            Map.entry("reconnaissance", 1),
            Map.entry("recon", 1),
            Map.entry("scan", 1),
            Map.entry("probe", 1),
            Map.entry("initial_access", 2),
            Map.entry("auth_failure", 2),
            Map.entry("brute_force", 2),
            Map.entry("exploitation", 3),
            Map.entry("exploit", 3),
            Map.entry("execution", 4),
            Map.entry("persistence", 5),
            Map.entry("privilege_escalation", 6),
            Map.entry("lateral_movement", 7),
            Map.entry("collection", 8),
            Map.entry("exfiltration", 9),
            Map.entry("exfil", 9),
            Map.entry("command_and_control", 10),
            Map.entry("c2", 10)
    );

    private final IpReputationService reputationService;
    private final OsintCollectorAgent osintAgent;

    /** Active attack campaigns keyed by campaign ID. */
    private final Map<String, AttackCampaign> activeCampaigns = new ConcurrentHashMap<>();

    /** Correlated alerts generated by this agent. */
    private final Deque<CorrelatedAlert> correlatedAlerts =
            new ArrayDeque<>();
    private static final int MAX_CORRELATED_ALERTS = 500;

    @Value("${ai.agents.correlation.window-hours:24}")
    private int correlationWindowHours;

    @Value("${ai.agents.correlation.kill-chain-threshold:3}")
    private int killChainThreshold;

    public ThreatCorrelationAgent(IpReputationService reputationService,
                                  OsintCollectorAgent osintAgent) {
        super("threat-correlation", "Threat Correlation Agent", AgentPriority.CRITICAL);
        this.reputationService = reputationService;
        this.osintAgent = osintAgent;
    }

    @Override
    public void execute() {
        int correlated = 0;

        correlated += correlateIpAcrossFeeds();
        correlated += detectKillChainProgression();
        correlated += clusterRelatedAlerts();
        updateCampaignTracking();
        expireOldCampaigns();

        itemsProcessed.addAndGet(correlated);

        if (correlated > 0) {
            log.info("Threat correlation complete: {} new correlations, {} active campaigns",
                    correlated, activeCampaigns.size());
        }
    }

    @Override
    protected String getSchedule() {
        return "every 2 minutes";
    }

    // ── Cross-Feed IP Correlation ─────────────────────────────────────

    /**
     * Finds IPs that appear in multiple threat intelligence sources.
     * Multi-source corroboration significantly increases confidence.
     *
     * @return number of new multi-source correlations found
     */
    private int correlateIpAcrossFeeds() {
        int correlations = 0;

        // Examine IPs with low reputation that have OSINT tags
        List<Map<String, Object>> threats = reputationService.getTopThreats(200);

        for (Map<String, Object> threat : threats) {
            String ip = (String) threat.get("ip");
            if (ip == null) continue;

            @SuppressWarnings("unchecked")
            List<String> tags = (List<String>) threat.getOrDefault("tags", List.of());

            // Count distinct OSINT sources
            Set<String> osintSources = tags.stream()
                    .filter(t -> t.startsWith("osint:"))
                    .map(t -> t.substring(6))
                    .collect(Collectors.toSet());

            if (osintSources.size() >= 2) {
                // Multi-source confirmed — increase severity
                IpReputation rep = reputationService.getOrCreate(ip);

                boolean alreadyTagged = tags.stream()
                        .anyMatch(t -> t.startsWith("correlated:multi_source"));
                if (!alreadyTagged) {
                    rep.addTag("correlated:multi_source_" + osintSources.size());
                    // Further penalize multi-source confirmed threats
                    rep.adjustScore(-5.0 * osintSources.size());

                    ThreatLevel level = osintSources.size() >= 3
                            ? ThreatLevel.CRITICAL : ThreatLevel.HIGH;

                    addCorrelatedAlert(new CorrelatedAlert(
                            UUID.randomUUID().toString(),
                            "Multi-source threat: " + ip,
                            "IP " + ip + " confirmed malicious by " + osintSources.size()
                                    + " independent sources: " + osintSources,
                            level,
                            ip,
                            "multi_source_correlation",
                            osintSources,
                            Instant.now()
                    ));

                    correlations++;
                    log.warn("Multi-source threat confirmed: {} (sources: {})", ip, osintSources);
                }
            }
        }

        return correlations;
    }

    // ── Kill Chain Detection ──────────────────────────────────────────

    /**
     * Groups recent events by source IP and looks for MITRE ATT&CK tactic
     * progression within the correlation window.
     *
     * @return number of kill chain progressions detected
     */
    private int detectKillChainProgression() {
        int detections = 0;
        List<Map<String, Object>> threats = reputationService.getTopThreats(500);

        for (Map<String, Object> threat : threats) {
            String ip = (String) threat.get("ip");
            if (ip == null) continue;

            @SuppressWarnings("unchecked")
            List<String> tags = (List<String>) threat.getOrDefault("tags", List.of());

            // Map tags to kill chain stages
            Set<Integer> observedStages = new TreeSet<>();
            for (String tag : tags) {
                String normalizedTag = tag.toLowerCase().replace("blocked:", "")
                        .replace("auto:", "").replace("osint:", "");
                for (Map.Entry<String, Integer> entry : KILL_CHAIN_STAGES.entrySet()) {
                    if (normalizedTag.contains(entry.getKey())) {
                        observedStages.add(entry.getValue());
                    }
                }
            }

            // Check for progression: N+ distinct stages observed
            if (observedStages.size() >= killChainThreshold) {
                IpReputation rep = reputationService.getOrCreate(ip);
                boolean alreadyDetected = tags.stream()
                        .anyMatch(t -> t.startsWith("correlated:kill_chain"));
                if (!alreadyDetected) {
                    rep.addTag("correlated:kill_chain_" + observedStages.size() + "_stages");
                    rep.adjustScore(-20.0);

                    // Auto-block if 4+ stages detected
                    if (observedStages.size() >= 4) {
                        reputationService.blockIp(ip, "auto:kill_chain_progression");
                    }

                    addCorrelatedAlert(new CorrelatedAlert(
                            UUID.randomUUID().toString(),
                            "Kill chain progression: " + ip,
                            "IP " + ip + " exhibits " + observedStages.size()
                                    + " stages of attack progression: stages " + observedStages,
                            ThreatLevel.CRITICAL,
                            ip,
                            "kill_chain_progression",
                            Set.of("stages:" + observedStages),
                            Instant.now()
                    ));

                    detections++;
                    log.error("KILL CHAIN detected from {}: {} stages — {}",
                            ip, observedStages.size(), observedStages);
                }
            }
        }

        return detections;
    }

    // ── Alert Clustering ──────────────────────────────────────────────

    /**
     * Clusters recent correlated alerts by shared IOCs, temporal proximity,
     * and source subnet overlap.
     *
     * @return number of new clusters formed
     */
    private int clusterRelatedAlerts() {
        int newClusters = 0;
        Instant cutoff = Instant.now().minus(1, ChronoUnit.HOURS);

        List<CorrelatedAlert> recent;
        synchronized (correlatedAlerts) {
            recent = correlatedAlerts.stream()
                    .filter(a -> a.detectedAt().isAfter(cutoff))
                    .toList();
        }

        if (recent.size() < 2) {
            return 0;
        }

        // Group by /24 subnet
        Map<String, List<CorrelatedAlert>> subnetGroups = new HashMap<>();
        for (CorrelatedAlert alert : recent) {
            String subnet = extractSubnet(alert.sourceIp());
            subnetGroups.computeIfAbsent(subnet, k -> new ArrayList<>()).add(alert);
        }

        for (Map.Entry<String, List<CorrelatedAlert>> entry : subnetGroups.entrySet()) {
            List<CorrelatedAlert> group = entry.getValue();
            if (group.size() >= 3) {
                String subnet = entry.getKey();
                String campaignId = "campaign-" + subnet.replace(".", "-");

                if (!activeCampaigns.containsKey(campaignId)) {
                    Set<String> involvedIps = group.stream()
                            .map(CorrelatedAlert::sourceIp)
                            .collect(Collectors.toSet());

                    AttackCampaign campaign = new AttackCampaign(
                            campaignId,
                            "Coordinated activity from subnet " + subnet,
                            involvedIps,
                            group.size(),
                            group.stream().map(CorrelatedAlert::detectedAt)
                                    .min(Instant::compareTo).orElse(Instant.now()),
                            Instant.now()
                    );
                    activeCampaigns.put(campaignId, campaign);
                    newClusters++;

                    log.warn("New attack campaign detected: {} — {} IPs, {} alerts from subnet {}",
                            campaignId, involvedIps.size(), group.size(), subnet);
                }
            }
        }

        return newClusters;
    }

    // ── Campaign Tracking ─────────────────────────────────────────────

    /**
     * Updates existing campaigns with new alert data and tracks progression.
     */
    private void updateCampaignTracking() {
        for (AttackCampaign campaign : activeCampaigns.values()) {
            // Check if any campaign IP has been blocked
            long blockedCount = campaign.involvedIps().stream()
                    .filter(reputationService::isBlocked)
                    .count();

            if (blockedCount == campaign.involvedIps().size()) {
                log.info("Campaign {} fully mitigated — all {} IPs blocked",
                        campaign.campaignId(), campaign.involvedIps().size());
            }
        }
    }

    /**
     * Expires campaigns that have had no new activity in the correlation window.
     */
    private void expireOldCampaigns() {
        Instant expiryCutoff = Instant.now().minus(correlationWindowHours, ChronoUnit.HOURS);
        activeCampaigns.entrySet().removeIf(entry -> {
            boolean expired = entry.getValue().lastUpdated().isBefore(expiryCutoff);
            if (expired) {
                log.info("Expiring stale campaign: {}", entry.getKey());
            }
            return expired;
        });
    }

    // ── Helpers ───────────────────────────────────────────────────────

    private void addCorrelatedAlert(CorrelatedAlert alert) {
        synchronized (correlatedAlerts) {
            correlatedAlerts.addFirst(alert);
            while (correlatedAlerts.size() > MAX_CORRELATED_ALERTS) {
                correlatedAlerts.pollLast();
            }
        }
    }

    /**
     * Extracts the /24 subnet from an IP address (e.g. "1.2.3.4" -> "1.2.3").
     */
    private String extractSubnet(String ip) {
        if (ip == null || !ip.contains(".")) {
            return "unknown";
        }
        int lastDot = ip.lastIndexOf('.');
        return lastDot > 0 ? ip.substring(0, lastDot) : ip;
    }

    // ── Public Accessors ──────────────────────────────────────────────

    /**
     * Returns all currently active attack campaigns.
     *
     * @return unmodifiable collection of active campaigns
     */
    public Collection<AttackCampaign> getActiveCampaigns() {
        return Collections.unmodifiableCollection(activeCampaigns.values());
    }

    /**
     * Returns the most recent correlated alerts.
     *
     * @param limit maximum number of alerts to return
     * @return list of recent correlated alerts
     */
    public List<CorrelatedAlert> getRecentCorrelatedAlerts(int limit) {
        synchronized (correlatedAlerts) {
            return correlatedAlerts.stream()
                    .limit(limit)
                    .toList();
        }
    }

    // ── Nested Records ────────────────────────────────────────────────

    /**
     * A correlated alert generated from cross-source analysis.
     */
    public record CorrelatedAlert(
            String alertId,
            String title,
            String description,
            ThreatLevel threatLevel,
            String sourceIp,
            String correlationType,
            Set<String> relatedSources,
            Instant detectedAt
    ) {}

    /**
     * An attack campaign composed of multiple correlated alerts
     * from related sources.
     */
    public record AttackCampaign(
            String campaignId,
            String description,
            Set<String> involvedIps,
            int alertCount,
            Instant firstSeen,
            Instant lastUpdated
    ) {}
}
