package com.filetransfer.sentinel.reporter;

import com.filetransfer.sentinel.config.SentinelConfig;
import com.filetransfer.sentinel.entity.SentinelFinding;
import com.filetransfer.sentinel.repository.SentinelFindingRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.*;

@Service
@RequiredArgsConstructor
@Slf4j
public class GitHubReporter {

    private final SentinelConfig config;
    private final SentinelFindingRepository findingRepository;
    private final ObjectMapper objectMapper;

    @Async
    public void report(SentinelFinding finding) {
        SentinelConfig.GitHub gh = config.getGithub();
        if (!gh.isEnabled() || gh.getToken() == null || gh.getToken().isBlank()) {
            log.debug("GitHubReporter: disabled or no token configured");
            return;
        }

        try {
            String issueUrl = createIssue(finding);
            if (issueUrl != null) {
                finding.setGithubIssueUrl(issueUrl);
                finding.setStatus("REPORTED");
                findingRepository.save(finding);
                log.info("GitHubReporter: created issue for finding '{}': {}", finding.getTitle(), issueUrl);
            }
        } catch (Exception e) {
            log.warn("GitHubReporter: failed to create issue: {}", e.getMessage());
        }
    }

    private String createIssue(SentinelFinding finding) throws Exception {
        SentinelConfig.GitHub gh = config.getGithub();
        String apiUrl = String.format("https://api.github.com/repos/%s/%s/issues", gh.getOwner(), gh.getRepo());

        String body = buildIssueBody(finding);
        List<String> labels = buildLabels(finding);

        Map<String, Object> issue = new LinkedHashMap<>();
        issue.put("title", String.format("[Sentinel] [%s] %s", finding.getSeverity(), finding.getTitle()));
        issue.put("body", body);
        issue.put("labels", labels);

        HttpURLConnection conn = (HttpURLConnection) new URL(apiUrl).openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setRequestProperty("Authorization", "Bearer " + gh.getToken());
        conn.setRequestProperty("X-GitHub-Api-Version", "2022-11-28");
        conn.setRequestProperty("Accept", "application/vnd.github+json");
        conn.setConnectTimeout(10000);
        conn.setReadTimeout(10000);
        conn.setDoOutput(true);
        conn.getOutputStream().write(objectMapper.writeValueAsBytes(issue));

        int code = conn.getResponseCode();
        if (code == 201) {
            @SuppressWarnings("unchecked")
            Map<String, Object> response = objectMapper.readValue(conn.getInputStream(), Map.class);
            return (String) response.get("html_url");
        } else {
            log.warn("GitHubReporter: HTTP {} creating issue", code);
            return null;
        }
    }

    private String buildIssueBody(SentinelFinding finding) {
        StringBuilder sb = new StringBuilder();
        sb.append("## Platform Sentinel Finding\n\n");
        sb.append("| Field | Value |\n|---|---|\n");
        sb.append("| **Analyzer** | ").append(finding.getAnalyzer()).append(" |\n");
        sb.append("| **Rule** | `").append(finding.getRuleName()).append("` |\n");
        sb.append("| **Severity** | ").append(severityEmoji(finding.getSeverity())).append(" ").append(finding.getSeverity()).append(" |\n");
        sb.append("| **Detected** | ").append(finding.getCreatedAt()).append(" |\n");

        if (finding.getAffectedService() != null) {
            sb.append("| **Service** | ").append(finding.getAffectedService()).append(" |\n");
        }
        if (finding.getAffectedAccount() != null) {
            sb.append("| **Account** | ").append(finding.getAffectedAccount()).append(" |\n");
        }
        if (finding.getTrackId() != null) {
            sb.append("| **Track ID** | `").append(finding.getTrackId()).append("` |\n");
        }

        sb.append("\n### Description\n\n").append(finding.getDescription()).append("\n");

        if (finding.getEvidence() != null) {
            sb.append("\n### Evidence\n\n```json\n").append(finding.getEvidence()).append("\n```\n");
        }

        sb.append("\n### Recommended Action\n\n");
        sb.append(recommendAction(finding));
        sb.append("\n\n---\n*Generated by Platform Sentinel — autonomous observer service*\n");

        return sb.toString();
    }

    private List<String> buildLabels(SentinelFinding finding) {
        List<String> labels = new ArrayList<>();
        labels.add("sentinel");
        labels.add(finding.getAnalyzer().toLowerCase());
        labels.add(finding.getSeverity().toLowerCase());
        if (finding.getAffectedService() != null) {
            labels.add(finding.getAffectedService());
        }
        return labels;
    }

    private String severityEmoji(String severity) {
        return switch (severity) {
            case "CRITICAL" -> "\uD83D\uDD34";
            case "HIGH" -> "\uD83D\uDFE0";
            case "MEDIUM" -> "\uD83D\uDFE1";
            default -> "\uD83D\uDD35";
        };
    }

    private String recommendAction(SentinelFinding finding) {
        return switch (finding.getRuleName()) {
            case "login_failure_spike" -> "1. Check audit logs for targeted accounts\n2. Review source IPs for patterns\n3. Consider temporary IP blocking if brute-force detected";
            case "account_lockout" -> "1. Verify with account owner if lockout is expected\n2. Reset if legitimate user\n3. Investigate if suspicious";
            case "integrity_mismatch" -> "1. **URGENT**: Verify file integrity manually\n2. Check disk health and network stability\n3. Re-transfer affected files";
            case "screening_hit" -> "1. **COMPLIANCE**: Review screening results immediately\n2. Quarantine affected files\n3. Notify compliance team";
            case "service_unhealthy" -> "1. Check service logs for errors\n2. Verify database connectivity\n3. Restart service if unresponsive";
            case "error_rate_spike" -> "1. Check transfer journey for common failure points\n2. Review recent configuration changes\n3. Check downstream service health";
            case "dlq_growth" -> "1. Review DLQ messages for error patterns\n2. Fix root cause before retrying\n3. Consider increasing consumer capacity";
            default -> "Review the finding evidence and take appropriate action based on severity.";
        };
    }
}
