import { onboardingApi } from './client'
export const getAccounts = () => onboardingApi.get('/api/accounts').then(r => r.data)
export const createAccount = (data) => onboardingApi.post('/api/accounts', data).then(r => r.data)
export const updateAccount = (id, data) => onboardingApi.put(`/api/accounts/${id}`, data).then(r => r.data)
export const deleteAccount = (id) => onboardingApi.delete(`/api/accounts/${id}`)
export const toggleAccount = (id, active) => onboardingApi.patch(`/api/accounts/${id}`, { active }).then(r => r.data)
export const getUsers = () => onboardingApi.get('/api/users').then(r => r.data)
export const updateUser = (id, data) => onboardingApi.patch(`/api/users/${id}`, data).then(r => r.data)
export const deleteUser = (id) => onboardingApi.delete(`/api/users/${id}`)
export const createUser = (data) => onboardingApi.post('/api/auth/register', data).then(r => r.data)
export const getFolderMappings = () => onboardingApi.get('/api/folder-mappings').then(r => r.data)
export const createFolderMapping = (data) => onboardingApi.post('/api/folder-mappings', data).then(r => r.data)
export const updateFolderMapping = (id, data) => onboardingApi.put(`/api/folder-mappings/${id}`, data).then(r => r.data)
export const deleteFolderMapping = (id) => onboardingApi.delete(`/api/folder-mappings/${id}`)

// Server Instances (all protocols: SFTP, FTP, FTP_WEB, HTTPS)
export const getServerInstances = () => onboardingApi.get('/api/servers').then(r => r.data)
export const getServerInstancesActive = () => onboardingApi.get('/api/servers?activeOnly=true').then(r => r.data)
export const getServerInstancesByProtocol = (protocol) => onboardingApi.get(`/api/servers?protocol=${protocol}`).then(r => r.data)
export const getServerInstancesActiveByProtocol = (protocol) => onboardingApi.get(`/api/servers?activeOnly=true&protocol=${protocol}`).then(r => r.data)
export const createServerInstance = (data) => onboardingApi.post('/api/servers', data).then(r => r.data)
export const updateServerInstance = (id, data) => onboardingApi.patch(`/api/servers/${id}`, data).then(r => r.data)
export const deleteServerInstance = (id) => onboardingApi.delete(`/api/servers/${id}`)
